### ISSUE TITLE
Invocations table and Satellite table (html)

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/paratexts#1]
Could you update both tables?
I have found more practical to have:

* one table with invocations only
* one table with satellite stanzas only

I have thus changed the tags `<seg function="satellite-stanza invocation">` to `<seg function="satellite-stanza">`.

This means we don't need any more

* the last column "Satellite Stanzas" in the table "Invocation"
* the last column "Invocation" in the table "Satellite Stanzas"

Could you also make the first column slightly larger so that a `<l>` is not distributed in two lines.

![image](https://user-images.githubusercontent.com/905870/203306850-f48d9146-23e8-495f-a1ba-959fbbcea5de.png)

[or if you prefer, so that, if a `<l>` is distributed in two lines, the second line is slightly indented]

**Comment by chchch** [comment]
Ok I updated the invocations and satellite stanzas tables. The column sizing is kind of automatic... I tried turning off line breaks for all <l> lines, but we ended up with really long lines because not all of the invocations/satellite stanzas have verse lines marked. I added a small indent at the beginning of each verse line instead... it should be more clear now.

**Comment by manufrancis** [comment]
Thanks!!!
Looks fine!!!
I will slowly add `<lg>` and `<l>`
